[2024-06-20T14:21:47.894+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T14:21:47.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hosp_pipeline.extract_transform_data manual__2024-06-20T14:16:43.251659+00:00 [queued]>
[2024-06-20T14:21:47.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hosp_pipeline.extract_transform_data manual__2024-06-20T14:16:43.251659+00:00 [queued]>
[2024-06-20T14:21:47.922+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T14:21:47.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_transform_data> on 2024-06-20 14:16:43.251659+00:00
[2024-06-20T14:21:47.942+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=135) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T14:21:47.944+0000] {standard_task_runner.py:63} INFO - Started process 137 to run task
[2024-06-20T14:21:47.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hosp_pipeline', 'extract_transform_data', 'manual__2024-06-20T14:16:43.251659+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/hospital_dag.py', '--cfg-path', '/tmp/tmp5ek2va77']
[2024-06-20T14:21:47.945+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask extract_transform_data
[2024-06-20T14:21:47.987+0000] {task_command.py:426} INFO - Running <TaskInstance: hosp_pipeline.extract_transform_data manual__2024-06-20T14:16:43.251659+00:00 [running]> on host 51c2a5215f2a
[2024-06-20T14:21:48.063+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hospital_admissions' AIRFLOW_CTX_DAG_ID='hosp_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T14:16:43.251659+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T14:16:43.251659+00:00'
[2024-06-20T14:21:48.065+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T14:21:48.068+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T14:21:48.069+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/hospital_dag.py", line 30, in extract_transform
    adm_df = pd.read_csv('Admission Data.csv')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Admission Data.csv'
[2024-06-20T14:21:48.083+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hosp_pipeline, task_id=extract_transform_data, run_id=manual__2024-06-20T14:16:43.251659+00:00, execution_date=20240620T141643, start_date=20240620T142147, end_date=20240620T142148
[2024-06-20T14:21:48.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task extract_transform_data ([Errno 2] No such file or directory: 'Admission Data.csv'; 137)
[2024-06-20T14:21:48.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T14:21:48.142+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T14:21:48.147+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
